---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ai-travel-advisor
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.6.1
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "ollama run orca-mini:3b" ]
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ai-travel-advisor
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
    - port: 80
      name: web 
      targetPort: 11434
      protocol: TCP
    - port: 11434
      name: http
      targetPort: 11434
      protocol: TCP